### PR TITLE
Fix quiting isearch mode via ctl-c

### PR DESCRIPTION
**Pull request by tacaswell**
This is port of / extension of the patches in https://bugs.python.org/issue24266

I am mostly opening this for easy discussion else where, I do not expect this to be merged.

The first commit is a direct merging of the two patches in the upstream issue, the second an backporting the functionality from rl 7 to the extension module.

### CODE REVIEW

**Comment by minrk** [comment]
Awesome, thanks @tacaswell!

**Comment by ludwigschwardt** [comment]
Would it make sense for me to merge it? I don't have the same compunction as Python.org if it manages to solve someone's problems. :-)

**Comment by tacaswell** [comment]
If you are willing to merge this it should probably be applied to atleast the 2.7 version and get a through review from someone who has more experience with the readline codebase.

**Comment by ludwigschwardt** [comment]
The latest gnureadline 8.0.0 release incorporates at least the first commit of this PR. The second commit is nice to have too, but the effort to maintain it (and the fact that IPython has moved away from readline anyway) counts against it. So I'm closing this for now and folks can still dig it up if needed. Thanks @tacaswell!

**Comment by tacaswell** [comment]
:+1:

**Pull request closed without merging**
